const db = require("./connection");
const { User, Post, Game } = require("../models");
const cleanDB = require("./cleanDB");

db.once("open", async () => {
  await cleanDB("User", "users");
  await cleanDB("Game", "games");
  await cleanDB("Post", "posts");

  console.log("Database cleaned");

  await User.insertMany([
    {
      username: "EvilKoala",
      email: "koala@gmail.com",
      password: "password12345",
      xboxTag: 'EvilKoala40',
      steamTag: 'SteamyBoy'
    },
    {
      username: "EvilTiger",
      email: "tiger@gmail.com",
      password: "password12345",
      psTag: 'EvilKoala39',
    },
    {
      username: "EvilCat",
      email: "cat@gmail.com",
      password: "password12345",
      nintendoTag: 'EvilKoala38',
    },
    {
      username: "EvilDuck",
      email: "duck@gmail.com",
      password: "password12345",
      appleTag: 'EvilKoala37',
    },
  ])

  await Post.insertMany([
    {
      author: 'EvilKoala',
      game: 'Animal Crossing',
      platform: 'Nintendo Switch',
      description: 'We doin hood rat shit in Animal Crossing',
      playersNeeded: '4',
    },
    {
      author: 'EvilKoala',
      game: 'Black Ops 6',
      platform: 'Xbox',
      description: 'We runnin some zombies',
      playersNeeded: '3',
    },
    {
      author: 'EvilKoala',
      game: 'Minecraft',
      platform: 'Playstation',
      description: 'Fighting the Ender Dragon',
      playersNeeded: '3',
    },
  ])


  const gameData = [
    {
      title: 'Animal Crossing: New Horizons',
      description: 'A life-simulation game where players build and manage their own island paradise, interacting with anthropomorphic animal villagers and customizing their environment.',
      image_url: 'https://m.media-amazon.com/images/I/81UfEdvf2kL.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Apex Legends',
      description: 'A free-to-play battle royale game where players choose from a roster of unique Legends, each with their own abilities, and compete in a team-based combat to be the last squad standing.',
      image_url: 'https://cdn.mobygames.com/covers/18989239-apex-legends-xbox-one-front-cover.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Assassin\'s Creed Odyssey',
      description: 'An action RPG set in Ancient Greece, where players take on the role of a mercenary, exploring vast open-world environments, engaging in battles, and influencing the story through decisions.',
      image_url: 'https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/1280x1280/products/3229566/6215929/TIARP17327__43941.1709701118.jpg?c=2',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Stadia'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Assassin\'s Creed Valhalla',
      description: 'An open-world action RPG where players take on the role of Eivor, a Viking raider exploring and conquering territories in England during the Viking Age.',
      image_url: 'https://m.media-amazon.com/images/I/61dog2zPmqL._AC_UF894,1000_QL80_.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Astral Chain',
      description: 'An action-adventure game where players control two characters simultaneously, a cop and their sentient weapon, to fight off interdimensional creatures and uncover a complex conspiracy.',
      image_url: 'https://m.media-amazon.com/images/M/MV5BZDNiNDNmZWQtMmNlMi00YjhiLTk0MjQtZDkxOTQwNDJmMzM2XkEyXkFqcGc@._V1_UY1200_CR85,0,630,1200_AL_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Astro\'s Playroom',
      description: 'A platformer game designed to showcase the PlayStation 5’s new DualSense controller, featuring Astro Bot as the main character on a journey through various themed worlds.',
      image_url: 'https://image.api.playstation.com/vulcan/ap/rnd/202010/0504/5PvLw0zv7VmGlHjBH4mhWZne.jpg',
      platform: ['PlayStation 5'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Battlefield V',
      description: 'A first-person shooter set during World War II, featuring large-scale battles, destructible environments, and dynamic weather systems.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/f/f0/Battlefield_V_standard_edition_box_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Bayonetta 2',
      description: 'An action hack-and-slash game starring Bayonetta, a witch who battles angels and demons in fast-paced combat, known for its stylish gameplay and over-the-top action.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/b/b1/Bayonetta_2_box_artwork.png',
      platform: ['Nintendo Switch', 'Wii U'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Bayonetta 3',
      description: 'The latest entry in the Bayonetta series, continuing the story of the powerful witch, featuring intense combat and new powers, along with a more expansive story.',
      image_url: 'https://m.media-amazon.com/images/I/717Nd4VBPyL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Bioshock Infinite',
      description: 'A first-person shooter set in the floating city of Columbia, where players take the role of Booker DeWitt, tasked with rescuing a mysterious girl named Elizabeth while unraveling a complex story.',
      image_url: 'https://blogs-images.forbes.com/erikkain/files/2012/12/cover_close-upDESIGN05.jpg',
      platform: ['PlayStation 3', 'Xbox 360', 'PC', 'Nintendo Switch'],
      release_year: 2013,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Black Myth: Wukong',
      description: 'An action RPG inspired by Chinese mythology, where players control the Monkey King, battling mythical creatures with dynamic combat and stunning visuals.',
      image_url: 'https://cdn1.epicgames.com/spt-assets/ca9ef1bcf2f54043baac351366aec677/black-myth-wukong-jjjfw.png',
      platform: ['PlayStation 5', 'Xbox Series X/S', 'PC'],
      release_year: 2024,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Blasphemous',
      description: 'A dark and atmospheric action-platformer with Metroidvania elements, set in a brutal world inspired by Spanish culture and religious imagery. Players control "The Penitent One" in a quest for redemption.',
      image_url: 'https://cdn1.epicgames.com/offer/eddb735dde6b47cda8193f2643cff886/EGS_Blasphemous_TheGameKitchen_S6_1200x1600-37265bbc691109595a2ff9b0c21ba8c7',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Bloodborne (via PS Now/PS Plus)',
      description: 'A gothic action RPG where players explore the cursed city of Yharnam, battling nightmarish creatures in challenging, fast-paced combat.',
      image_url: 'https://image.api.playstation.com/vulcan/img/rnd/202010/2614/Sy5e8DmeKIJVjlAGraPAJYkT.png',
      platform: ['PlayStation 4 (Playable on PC via PS Now/PS Plus)'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Borderlands 3',
      description: 'A first-person looter-shooter with a humorous and chaotic story. Players choose from four Vault Hunters to explore planets, defeat enemies, and collect vast amounts of loot.',
      image_url: 'https://m.media-amazon.com/images/I/81JkEWTnXQL._AC_UF894,1000_QL80_.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Call of Duty: Black Ops',
      description: 'A first-person shooter set during the Cold War era, featuring an intense campaign, multiplayer modes, and the introduction of the iconic Zombies mode.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/0/02/CoD_Black_Ops_cover.png',
      platform: ['PlayStation 3', 'Xbox 360', 'PC'],
      release_year: 2010,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Call of Duty: Black Ops II',
      description: 'The sequel to Black Ops, this game features a branching storyline set in the near future, alongside refined multiplayer and a new Zombies mode.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/0/05/Call_of_Duty_Black_Ops_II_box_artwork.png',
      platform: ['PlayStation 3', 'Xbox 360', 'PC'],
      release_year: 2012,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Call of Duty: Black Ops III',
      description: 'A futuristic shooter that introduces cybernetic enhancements, a co-op campaign, and robust multiplayer options, including an expanded Zombies mode.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/b/b1/Black_Ops_3.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Call of Duty: Modern Warfare II',
      description: 'A sequel in the Modern Warfare sub-series, featuring an immersive single-player campaign and highly competitive multiplayer modes, along with a focus on realism and tactical gameplay.',
      image_url: 'https://imageio.forbes.com/specials-images/imageserve/628d337e791f9767c05ca2e7/1--2-/960x0.jpg?height=887&width=711&fit=bounds',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Call of Duty: Warzone',
      description: 'A free-to-play battle royale game set in the Call of Duty universe, offering large-scale battles with up to 150 players and various game modes.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/6/65/COD_Warzone_Cover_Art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Celeste',
      description: 'A critically acclaimed indie platformer about a young woman, Madeline, who climbs the titular mountain while confronting her inner struggles. Features tight controls and challenging levels.',
      image_url: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Celeste_box_art_full.png/1200px-Celeste_box_art_full.png',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Chivalry 2',
      description: 'A multiplayer medieval combat game, offering large-scale, chaotic battles with swords, axes, and bows in first- or third-person perspective.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Chivalry_2_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Cities: Skylines',
      description: 'A city-building simulation game where players design and manage their own cities, balancing infrastructure, zoning, and citizen needs.',
      image_url: 'https://cdn1.epicgames.com/6009be9994c2409099588cde6f3a5ed0/offer/EGS_CitiesSkylinesDeluxeEditionUpgradePack_ColossalOrder_DLC_S2-1200x1600-1c4b7a1da9959e9cf07b4f23c44d0fed.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Control',
      description: 'A third-person action-adventure game with a surreal storyline. Players assume the role of Jesse Faden, exploring a mysterious government building filled with supernatural phenomena.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/e/e5/Control_game_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Counter-Strike: Global Offensive',
      description: 'A highly popular multiplayer first-person shooter, known for its competitive gameplay and team-based objectives. Players join either the Terrorists or Counter-Terrorists to complete missions.',
      image_url: 'https://i0.wp.com/www.thunderlan.org/wp-content/uploads/2017/08/Counter-Strike-Global-Offensive-cover.jpg?fit=450%2C600&ssl=1',
      platform: ['PC', 'macOS', 'Linux'],
      release_year: 2012,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Cuphead',
      description: 'A run-and-gun platformer with a unique hand-drawn 1930s cartoon art style. Players take on challenging boss battles as Cuphead and Mugman to repay a debt to the devil.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Cuphead_%28artwork%29.png',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Cyberpunk 2077',
      description: 'An open-world RPG set in the dystopian Night City, where players assume the role of V, a mercenary with cybernetic enhancements, exploring a futuristic world filled with choices and consequences.',
      image_url: 'https://cyberpunklibrarian.com/infopump/images/33.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Cyberpunk 2077 (Next-Gen Update)',
      description: 'A major update to Cyberpunk 2077, enhancing visuals, gameplay, and performance specifically for next-gen consoles and high-end PCs.',
      image_url: 'https://assetsio.gnwcdn.com/co4hk8.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp',
      platform: ['PlayStation 5', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'DOOM Eternal',
      description: 'A fast-paced first-person shooter where players take on the role of the Doom Slayer, battling demonic hordes to save humanity from Hell’s invasion.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/9/9d/Cover_Art_of_Doom_Eternal.png',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC', 'Stadia'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dark Souls III',
      description: 'An action RPG known for its challenging gameplay and dark fantasy setting. Players explore a world filled with formidable enemies and intricate level designs.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/Dark_souls_3_cover_art.jpg/220px-Dark_souls_3_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dead by Daylight',
      description: 'A multiplayer horror game where one player assumes the role of a killer, while four survivors work together to escape. It features iconic characters from horror franchises.',
      image_url: 'https://cdn1.epicgames.com/offer/611482b8586142cda48a0786eb8a127c/EGS_DeadbyDaylight_BehaviourInteractive_S2_1200x1600-a1c30209e3b9fb63144daa9b5670f503',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dead Cells',
      description: 'A rogue-lite, Metroidvania-inspired action platformer where players control a reanimated corpse exploring a procedurally generated castle, fighting enemies, and collecting upgrades.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1f/Dead_cells_cover_art.png',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC', 'mobile'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Deathloop',
      description: 'A first-person action game where two assassins are trapped in a time loop. Players must eliminate eight targets in one loop while avoiding a rival assassin controlled by the AI or another player.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/c/cb/Deathloop_cover_art.jpg',
      platform: ['PlayStation 5', 'PC', 'Xbox Series X/S'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Demon\'s Souls (Remake)',
      description: 'A remake of the iconic action RPG, featuring enhanced visuals and gameplay while retaining the original’s challenging combat and atmospheric world.',
      image_url: 'https://image.api.playstation.com/vulcan/img/rnd/202011/1717/qHFrrJINxIfsvIyudYAyjfDq.png',
      platform: ['PlayStation 5'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Destiny 2',
      description: 'A free-to-play online multiplayer first-person shooter with RPG elements, featuring cooperative raids, competitive PvP modes, and an expansive sci-fi universe.',
      image_url: 'https://i.ebayimg.com/images/g/sMcAAOSwVAhiItMQ/s-l400.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Destruction AllStars',
      description: 'A vehicular combat game where players use vehicles and on-foot abilities to smash opponents in arena battles. Features diverse characters with unique skills.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8c/Destruction_AllStars_cover_art.jpg/220px-Destruction_AllStars_cover_art.jpg',
      platform: ['PlayStation 5'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Disco Elysium',
      description: 'A narrative-driven RPG where players take on the role of a detective solving a murder in a surreal, dystopian world. Known for its deep dialogue system and player choices.',
      image_url: 'https://shop.discoelysium.com/cdn/shop/products/Final-Cut-poster_grande.png?v=1607618522',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Divinity: Original Sin 2',
      description: 'A critically acclaimed RPG with turn-based combat, set in a richly detailed fantasy world. Players can create their characters or choose from pre-defined heroes with deep storylines.',
      image_url: 'https://static.wikia.nocookie.net/english-otome-games/images/4/48/Divinity_Original_Sin_2_cover_art.jpg/revision/latest?cb=20220128230558',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Donkey Kong Country: Tropical Freeze',
      description: 'A vibrant platformer where players help Donkey Kong and his family save their home from invading Snowmads, featuring challenging levels and co-op gameplay.',
      image_url: 'https://m.media-amazon.com/images/M/MV5BMzNkNzBlMjEtMzE2OC00MDgxLWE5MzQtYzRmYTZjNzBiOGYxXkEyXkFqcGc@._V1_.jpg',
      platform: ['Nintendo Switch', 'Wii U'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dota 2',
      description: 'A competitive multiplayer online battle arena (MOBA) game where two teams of five players face off to destroy the opposing team\'s Ancient.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/3/31/Dota_2_Steam_artwork.jpg',
      platform: ['PC', 'macOS', 'Linux'],
      release_year: 2013,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dragon Age: Inquisition',
      description: 'A fantasy RPG where players lead the Inquisition to restore order in a world torn by civil war and a breach to the Fade, the magical realm.',
      image_url: 'https://m.media-amazon.com/images/I/71NBP-qVhUL.jpg',
      platform: ['PlayStation 3', 'PlayStation 4', 'Xbox 360', 'Xbox One', 'PC'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dragon Ball FighterZ',
      description: 'A fast-paced fighting game with 3v3 team battles, featuring characters from the Dragon Ball universe. Known for its stunning anime-style visuals and accessible gameplay.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/a/ad/DBFZ_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dragon Quest XI S: Echoes of an Elusive Age',
      description: 'A turn-based JRPG with a rich story, charming characters, and a vibrant world. This "S" version adds new content, including an orchestrated soundtrack and additional story arcs.',
      image_url: 'https://cdn1.epicgames.com/94a50905f377470c84c8e4b7c38f9cdd/offer/EGS_DRAGONQUESTXISEchoesofanElusiveAge_SquareEnix_S2-1200x1600-85fb72821e496f64e3945969c6fd4290.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC', 'Stadia'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Dying Light 2: Stay Human',
      description: 'An open-world action RPG focusing on parkour and melee combat in a zombie-infested city. Players make impactful choices that shape the story and the world.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/6/6d/Dying_Light_2_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Nintendo Switch (cloud version)'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Elden Ring',
      description: 'An open-world action RPG by FromSoftware, co-written with George R.R. Martin. Players explore the Lands Between, battling fierce enemies and uncovering deep lore.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'F1 2020',
      description: 'A Formula 1 racing simulation featuring all official teams, drivers, and circuits from the 2020 season, with enhanced customization and career options.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/8/84/F1_2020_Cover.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Stadia'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'FIFA 23',
      description: 'The final entry in EA Sports’ FIFA series, featuring enhanced HyperMotion2 technology, cross-play functionality, and updated rosters for an authentic soccer experience.',
      image_url: 'https://fifauteam.com/images/covers/fifa23/standard-cg.webp',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia', 'Nintendo Switch (Legacy Edition)'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Factorio',
      description: 'A strategy and simulation game where players build and manage automated factories on an alien planet, harvesting resources and defending against hostile creatures.',
      image_url: 'https://i.redd.it/lvwd7gkc4jy71.png',
      platform: ['PC', 'macOS', 'Linux', 'Nintendo Switch'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Fallout 4',
      description: 'A post-apocalyptic RPG set in a nuclear wasteland. Players assume the role of a survivor exploring the world, building settlements, and shaping the future of the Commonwealth.',
      image_url: 'https://m.media-amazon.com/images/I/91CVpBwQYfL.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Far Cry 5',
      description: 'An open-world first-person shooter where players fight against a fanatical doomsday cult in the fictional Hope County, Montana, using various weapons, vehicles, and companions.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/0/03/Far_Cry_5_boxshot.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Stadia'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Far Cry 6',
      description: 'Set in the fictional country of Yara, players join the resistance to overthrow a dictator in a tropical open world filled with guerrilla warfare and customizable weapons.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/3/35/Far_cry_6_cover.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Far Cry Primal',
      description: 'A spin-off of the Far Cry series set in the Stone Age, where players control a hunter trying to survive and build a tribe in a prehistoric world.',
      image_url: 'https://m.media-amazon.com/images/M/MV5BYmE5MDY4ZDQtYmM0Yi00NzMyLWI4MmItZTU5ZTEyY2Q3Yjc3XkEyXkFqcGc@._V1_.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Final Fantasy VII Remake Intergrade',
      description: 'An enhanced and expanded version of the Final Fantasy VII Remake, featuring improved graphics, a new photo mode, and additional content with the Intermission DLC.',
      image_url: 'https://cdn11.bigcommerce.com/s-6rs11v9w2d/images/stencil/1280x1280/products/1055/2776/df5313d5528cafec58d0163d3c4036e7__21577.1663105531.jpg?c=1',
      platform: ['PlayStation 5', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Final Fantasy XIV',
      description: 'A critically acclaimed MMORPG with an expansive storyline, frequent updates, and various activities such as crafting, raiding, and exploration.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/4/45/Final_Fantasy_XIV_box_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'PC', 'macOS'],
      release_year: 2013,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Final Fantasy XVI',
      description: 'An action-packed RPG set in a dark fantasy world where players follow the story of Clive Rosfield and navigate political intrigue, epic battles, and powerful Eikons.',
      image_url: 'https://cdn11.bigcommerce.com/s-6rs11v9w2d/images/stencil/1280x1280/products/2752/13555/FFXVI_Packshot_SQ-500x718_US__23623.1694706908.jpg?c=1',
      platform: ['PlayStation 5'],
      release_year: 2023,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Fire Emblem: Three Houses',
      description: 'A tactical RPG where players act as a professor at a monastery, teaching and guiding students through battles and political conflicts in the land of Fódlan.',
      image_url: 'https://external-preview.redd.it/kGXfnFjjOl2hOQLg2cDlIIcVcVVAFxMix36syx3UHyU.jpg?width=640&crop=smart&auto=webp&s=49d32a3b25b951c531d387e1d8d88a5c425e9ea0',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Fortnite',
      description: 'A battle royale game where players compete to be the last one standing in a colorful, ever-changing map, featuring building mechanics and crossovers with popular franchises.',
      image_url: 'https://assetsio.gnwcdn.com/co2ekt.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC', 'mobile'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Forza Horizon 4',
      description: 'An open-world racing game set in a fictional version of Great Britain, featuring dynamic seasons, hundreds of cars, and a vibrant online multiplayer mode.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/8/87/Forza_Horizon_4_cover.jpg',
      platform: ['Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Forza Horizon 5',
      description: 'An open-world racing game set in a stunningly detailed rendition of Mexico. The game offers a vast array of cars, dynamic seasons, and multiplayer events.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/8/86/Forza_Horizon_5_cover_art.jpg',
      platform: ['Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Gears 5',
      description: 'The fifth entry in the Gears of War franchise, focusing on Kait Diaz as she uncovers secrets about her family and the Locust. The game features both a single-player campaign and robust multiplayer modes.',
      image_url: 'https://cdn.mobygames.com/covers/11078555-gears-5-windows-apps-front-cover.jpg',
      platform: ['Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Gears of War 4',
      description: 'A third-person shooter set after the events of Gears of War 3, focusing on the next generation of soldiers in the Gears universe as they battle a new enemy.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/f/ff/Gears_of_War_4.jpg',
      platform: ['Xbox One', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ghost of Tsushima: Director’s Cut',
      description: 'An enhanced version of Ghost of Tsushima, set in feudal Japan, where players control Jin Sakai in a quest to protect his home from Mongol invaders. The Director\'s Cut adds additional content, including an expansion set on the Iki Island.',
      image_url: 'https://cdn1.epicgames.com/offer/6e6aa039c73347b885803de65ac5d3db/EGS_GhostofTsushima_SuckerPunchProductions_S2_1200x1600-e23e02c1d70be7b528dba50860f87d39',
      platform: ['PlayStation 4', 'PlayStation 5'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ghostwire: Tokyo',
      description: 'An action-adventure game set in a supernatural version of Tokyo, where players fight off mysterious spirits and solve the mystery behind the city\'s mass disappearance.',
      image_url: 'https://store-images.s-microsoft.com/image/apps.27628.14258547668150351.c20c8953-e19e-40f6-8081-ab904c694484.af912fca-0b76-4ec7-98f8-b820a3ff593b',
      platform: ['PlayStation 5', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'God of War Ragnarök',
      description: 'The sequel to God of War (2018), following Kratos and his son Atreus as they navigate the coming of Ragnarök, the end of the world in Norse mythology.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/e/ee/God_of_War_Ragnar%C3%B6k_cover.jpg',
      platform: ['PlayStation 4', 'PlayStation 5'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Gran Turismo 7',
      description: 'The latest entry in the Gran Turismo series, offering an authentic racing experience with a variety of cars and tracks, including extensive customization and detailed graphics.',
      image_url: 'https://image.api.playstation.com/vulcan/ap/rnd/202109/1321/3mjMyRiJaq8lw1EFWiTCUJRV.png',
      platform: ['PlayStation 4', 'PlayStation 5'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Gran Turismo Sport',
      description: 'A racing simulation game with a focus on online competitive racing, offering a large variety of cars, tracks, and a real-world sports-like environment.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/9/96/GT_Sport_cover_art.jpg',
      platform: ['PlayStation 4'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Grand Theft Auto V',
      description: 'An open-world action-adventure game where players control three criminals as they navigate heists, missions, and the chaotic world of Los Santos. It includes a robust online mode, GTA Online.',
      image_url: 'https://i.imgur.com/05x5tvj.png',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2013,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Hades',
      description: 'A rogue-like action game where players control Zagreus, the son of Hades, as he tries to escape the underworld, battling through procedurally generated levels with various weapons and powers.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Hades_cover_art.jpg/220px-Hades_cover_art.jpg',
      platform: ['Nintendo Switch', 'PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Half-Life: Alyx',
      description: 'A virtual reality first-person shooter set between the events of Half-Life and Half-Life 2, where players control Alyx Vance as she fights against the alien Combine forces.',
      image_url: 'https://www.cnet.com/a/img/resize/2b05dadb6d20f076c3c07aeebeaf5028b8b8fe75/hub/2019/11/21/19db7c73-c881-4bd4-bf96-8c2174feff67/box-art-flat.png?auto=webp&width=1200',
      platform: ['PC (VR)'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Halo: The Master Chief Collection',
      description: 'A collection of the main Halo titles, featuring updated graphics, multiplayer support, and all of the campaigns from Halo: Combat Evolved through Halo 4, with Halo: Reach and Halo: ODST added as well.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/Halo_TMCC_KeyArt_Vert_2019.png/220px-Halo_TMCC_KeyArt_Vert_2019.png',
      platform: ['Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Hellblade: Senua\'s Sacrifice',
      description: 'An action-adventure game that follows Senua, a warrior dealing with psychosis, as she embarks on a journey to rescue the soul of her deceased lover from the Norse underworld.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Hellblade_-_Senua%27s_Sacrifice.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC', 'Xbox Series X/S', 'PlayStation 5'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Hitman 3',
      description: 'The concluding entry in the World of Assassination trilogy, where players control Agent 47 as he takes on a series of high-profile assassination contracts across the globe.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/4/4b/Hitman_3_Packart.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Hollow Knight',
      description: 'A critically acclaimed 2D action-platformer set in a vast, interconnected world. Players control a small knight exploring the ruins of a forgotten kingdom, battling enemies and discovering hidden secrets.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/0/04/Hollow_Knight_first_cover_art.webp',
      platform: ['Nintendo Switch', 'PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Hollow Knight: Voidheart Edition',
      description: 'The Voidheart Edition of Hollow Knight includes the base game along with all the major DLC expansions, offering new areas, bosses, and gameplay features.',
      image_url: 'https://static.wikia.nocookie.net/hollowknight/images/e/e6/Hollow_Knight_VoidHeart_Edition_Xbox_One_Front_Cover.jpg/revision/latest?cb=20201215192046',
      platform: ['Nintendo Switch', 'PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Horizon Forbidden West',
      description: 'The sequel to Horizon Zero Dawn, where players once again control Aloy as she explores the dangerous, post-apocalyptic world to uncover the secrets behind a new threat to humanity.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/6/69/Horizon_Forbidden_West_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Hotline Miami Collection',
      description: 'A collection of the fast-paced, top-down shooters Hotline Miami and Hotline Miami 2: Wrong Number, featuring brutal combat, neon-soaked visuals, and a dark, surreal narrative.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/f/f4/Hotline_Miami_cover.png',
      platform: ['PlayStation 4', 'PlayStation Vita', 'Nintendo Switch', 'Xbox One', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Hyrule Warriors: Age of Calamity',
      description: 'A hack-and-slash action game set in The Legend of Zelda universe, serving as a prequel to Breath of the Wild, where players fight to defend Hyrule from the forces of Calamity Ganon.',
      image_url: 'https://m.media-amazon.com/images/I/81BDD8zIxhL.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Immortals Fenyx Rising',
      description: 'An open-world action RPG inspired by Greek mythology, where players control Fenyx, a young hero on a quest to save the Greek gods from the evil Titan Typhon.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/5/5f/Immortals_Fenyx_Rising_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Kena: Bridge of Spirits',
      description: 'An action-adventure game where players control Kena, a young spirit guide, as she explores a beautiful world to help spirits find peace, solving puzzles, and battling enemies.',
      image_url: 'https://cdn1.epicgames.com/7c53d7dc86494d5abcdc974b0ef0a843/offer/EGS_KenaBridgeofSpirits_EmberLab_S6-1200x1600-e701bd947727ee14b81626c7f9757e4f.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Kirby and the Forgotten Land',
      description: 'A 3D platformer where players control Kirby as he explores a mysterious world filled with ancient technology and powerful enemies, using his signature ability to copy powers.',
      image_url: 'https://target.scene7.com/is/image/Target/GUEST_a39a9def-90e2-408a-b478-cabdf22ba3d7?wid=488&hei=488&fmt=pjpeg',
      platform: ['Nintendo Switch'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'League of Legends',
      description: 'A highly competitive online multiplayer battle arena game where two teams of five players battle in strategic combat, aiming to destroy the opposing team\'s Nexus.',
      image_url: 'https://img.opencritic.com/game/9751/o/CtKWhFtW.jpg',
      platform: ['PC'],
      release_year: 2009,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Lego City Undercover',
      description: 'A sandbox adventure game set in a LEGO world, where players control Chase McCain, a police officer, as he solves crimes and uncovers the villainous schemes of criminals.',
      image_url: 'https://assetsio.gnwcdn.com/co5vx0.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp',
      platform: ['Nintendo Switch', 'PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Little Nightmares II',
      description: 'A suspense-filled puzzle-platformer where players control Mono, a young boy trapped in a distorted world, trying to escape while encountering terrifying creatures and environments.',
      image_url: 'https://image.api.playstation.com/vulcan/ap/rnd/202011/1819/m7gCTrMRQBTPHi87Mi3leVVY.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Luigi\'s Mansion',
      description: 'A classic action-adventure game in which Luigi explores a haunted mansion to rescue his brother Mario, using a vacuum-like device to capture ghosts and solve puzzles.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Lmbox.jpg',
      platform: ['GameCube'],
      release_year: 2001,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Luigi\'s Mansion 3',
      description: 'The third installment in the series, where Luigi embarks on a new adventure to rescue his friends from a haunted hotel. Featuring puzzle-solving, ghost-catching, and co-op multiplayer.',
      image_url: 'https://i.ebayimg.com/images/g/-8cAAOSwVZFfB0S-/s-l400.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Madden NFL 23',
      description: 'A sports simulation game based on American football, offering realistic gameplay, updated rosters, and game modes such as Franchise and Ultimate Team.',
      image_url: 'https://media.contentapi.ea.com/content/dam/ea/madden-nfl/madden-nfl-23/news/common/copy-of-eas-madden23-gen5-ame-keyart-vert-cmyk.jpg.adapt.320w.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Mario + Rabbids Kingdom Battle',
      description: 'A turn-based strategy game that combines characters from Super Mario and Rabbids, where players use tactical combat to fight through the Mushroom Kingdom and stop an evil force.',
      image_url: 'https://m.media-amazon.com/images/I/81DEtGHy41L.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Mario Kart 8 Deluxe',
      description: 'A fast-paced kart racing game featuring Mario and other Nintendo characters, offering a wide variety of tracks, karts, and power-ups, along with multiplayer modes.',
      image_url: 'https://m.media-amazon.com/images/I/81iJG2js5-S._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Marvel's Spider-Man",
      description: 'An action-adventure game that lets players take control of Spider-Man in an open-world New York City, featuring a gripping story and fluid web-swinging mechanics.',
      image_url: 'https://image.api.playstation.com/vulcan/img/rnd/202011/0714/At7kpPioyCSPENS5x6gHesjR.png',
      platform: ['PlayStation 4', 'PlayStation 5'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: "Marvel's Spider-Man 2",
      description: 'The sequel to Marvel’s Spider-Man, expanding the story with both Peter Parker and Miles Morales as playable characters, alongside new powers and villains.',
      image_url: 'https://cdn.marvel.com/content/1x/marvelsspiderman2_lob_crd_02.jpg',
      platform: ['PlayStation 5'],
      release_year: 2023,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Mass Effect Legendary Edition',
      description: 'A remastered collection of the Mass Effect trilogy, featuring updated visuals and improved gameplay. Players control Commander Shepard as they navigate a galaxy at war against a mysterious threat.',
      image_url: 'https://cdn1.epicgames.com/offer/2a535f0e7c754dbe9157bf96adc62d56/EGS_MassEffectLegendaryEdition_BioWare_S2_1200x1600-c8286ed1e08b413e7cbdc190db5a589a',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Metroid Dread',
      description: 'The latest installment in the Metroid series, where players control Samus Aran as she explores an eerie planet to uncover secrets while battling robotic enemies and hostile aliens.',
      image_url: 'https://m.media-amazon.com/images/I/61GP7RW7tQL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Minecraft',
      description: 'A sandbox game where players can build, explore, and survive in a procedurally generated world made entirely of blocks. It features a creative mode and a survival mode, with a huge modding community.',
      image_url: 'https://static0.gamerantimages.com/wordpress/wp-content/uploads/2023/09/minecraft-game.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC', 'PlayStation 5', 'Xbox Series X/S', 'Mobile'],
      release_year: 2011,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Monster Hunter Rise',
      description: 'An action RPG where players take on the role of a monster hunter, tasked with tracking and defeating massive creatures across varied landscapes. The game introduces new mechanics, such as wirebugs and the Rampage mode.',
      image_url: 'https://buycheapplaycheap.com/wp-content/uploads/2022/01/Monster-Hunter-Rise.jpg',
      platform: ['Nintendo Switch', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Monster Hunter: Wilds',
      description: 'An expansive entry in the Monster Hunter series that emphasizes exploration, cooperative play, and battling massive creatures in diverse environments.',
      image_url: 'https://caniplaythat.com/wp-content/uploads/2024/11/boxart-monster-hunter-wilds.webp',
      platform: ['Xbox','Playstaion 5','PC'],
      release_year: 2025, 
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Monster Hunter: World',
      description: 'A critically acclaimed entry in the Monster Hunter series, where players explore an expansive world, hunt colossal monsters, and craft powerful gear from their remains.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Monster_Hunter_World_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Mortal Kombat 11',
      description: 'The latest entry in the brutal fighting series, known for its iconic characters, fatalities, and fast-paced combat. It introduces a new story mode and additional guest characters.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Mortal_Kombat_11_cover_art.png',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'NBA 2K23',
      description: 'A basketball simulation game offering realistic gameplay, a variety of modes including MyCareer and MyTeam, and a roster of current and legendary NBA players.',
      image_url: 'https://www.mkaugaming.com/wp-content/uploads/2022/07/NBA_2K23_DigitalDeluxe_1080x1920.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Need for Speed Heat',
      description: 'An open-world racing game that mixes legal daytime races with illegal nighttime street races, offering high-speed action and car customization.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/7/7f/Cover_Art_of_Need_for_Speed_Heat.png',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Nier Replicant ver.1.22474487139…',
      description: 'A remastered version of Nier Replicant, an action RPG that follows a young man on a quest to cure his sister from a mysterious disease, with deep philosophical themes and a unique combat system.',
      image_url: 'https://cdn11.bigcommerce.com/s-6rs11v9w2d/images/stencil/1280x1280/products/1100/3098/cabf9a309837904b86583c57c4429e30__73691.1684909821.jpg?c=1',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Nier: Automata',
      description: 'An action RPG set in a post-apocalyptic world where players control androids as they battle alien forces. The game features a rich narrative, fast combat, and multiple endings.',
      image_url: 'https://cdn11.bigcommerce.com/s-6rs11v9w2d/images/stencil/1280x1280/products/1104/3150/2aa10812eac23a04587883b3df08a1f7__43901.1693503017.jpg?c=1',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Nintendo Switch'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Nier: Automata – The End of YoRHa Edition',
      description: 'A special edition of Nier: Automata, which includes additional content such as new costumes and features, providing a definitive version of the game.',
      image_url: 'https://cdn11.bigcommerce.com/s-6rs11v9w2d/images/stencil/1280x1280/products/1759/14114/NieREndofYorha_ESRB_EN__93148.1683771317.jpg?c=1',
      platform: ['PlayStation 5', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ninja Gaiden: Master Collection',
      description: 'A collection of the Ninja Gaiden action games, featuring fast-paced combat, intense difficulty, and a storyline about a skilled ninja, Ryu Hayabusa, battling enemies with deadly precision.',
      image_url: 'https://gamerhash.com/storage/mobile-products/6Lq8haFO64zXSMeKzQxjLlhJCnJixcrjAX912rgR.jpeg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Nioh 2 Remastered',
      description: 'An action RPG set in a samurai-era world mixed with Japanese mythology. Players control a custom hero and fight through enemies and bosses using a wide variety of weapons and abilities.',
      image_url: 'https://assetsio.gnwcdn.com/co2slr.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp',
      platform: ['PlayStation 4', 'PlayStation 5', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'No Man\'s Sky',
      description: 'A space exploration game where players explore procedurally generated planets, gather resources, build bases, and encounter alien lifeforms in a vast, ever-expanding universe.',
      image_url: 'https://cdn.mobygames.com/covers/3556083-no-mans-sky-xbox-one-front-cover.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'PlayStation 5', 'Xbox Series X/S'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Octopath Traveler',
      description: 'A turn-based RPG where players control eight unique characters, each with their own stories and abilities. The game features beautiful pixel art and a deep, strategic combat system.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/3/34/Octopath_Traveler.jpg',
      platform: ['Nintendo Switch', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ori and the Will of the Wisps',
      description: 'A platformer with a beautiful hand-drawn art style and emotional storytelling. Players control Ori, a small guardian spirit, as they navigate through a lush world filled with puzzles, enemies, and exploration.',
      image_url: 'https://store-images.s-microsoft.com/image/apps.18799.14047496556148589.9fda5cef-7995-4dbb-a626-66d2ab3feb4f.1e167626-8b7d-47b4-9fe5-d06a43ac6677',
      platform: ['Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Outer Worlds',
      description: 'A first-person RPG set in an alternate future where mega-corporations control space colonies. Players create their own character and make choices that impact the story and the world around them.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/e/e7/The_Outer_Worlds_cover_art.png',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Outriders',
      description: 'A cooperative third-person shooter where players take on the role of a futuristic soldier with special powers, battling enemies in an apocalyptic world and focusing on loot-driven gameplay.',
      image_url: 'https://cdn11.bigcommerce.com/s-6rs11v9w2d/images/stencil/1280x1280/products/1108/3174/b9a4df7dba8e640025ac72bac27c43a5__35763.1675458016.jpg?c=1',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC', 'Stadia'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Overwatch 2',
      description: 'A hero-based multiplayer shooter that builds upon the original Overwatch, introducing new heroes, maps, and a story-driven co-op mode.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Overwatch_2_Steam_artwork.jpg/220px-Overwatch_2_Steam_artwork.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Pikmin 3 Deluxe',
      description: 'A real-time strategy game where players control groups of Pikmin to solve puzzles, gather resources, and defeat enemies. This deluxe edition includes new content and features.',
      image_url: 'https://www.nintendo.com/ph/switch/ampn/img/hero_sp.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Plants vs. Zombies',
      description: 'A tower defense game where players strategically place plants to defend their home from waves of comical yet menacing zombies. Each plant has unique abilities, and the game offers various modes, including Adventure, Mini-Games, and Survival.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/9/9c/PlantsvsZombiesCoverArt.jpg',
      platform: ['PC', 'Mac', 'Xbox 360', 'PlayStation 3', 'Nintendo DS', 'iOS', 'Android', 'PS Vita'],
      release_year: 2009,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Plants vs. Zombies: Battle for Neighborville',
      description: 'A third-person shooter featuring the iconic characters from Plants vs. Zombies, where players can engage in online multiplayer battles or play through an adventure mode in a quirky world.',
      image_url: 'https://store-images.s-microsoft.com/image/apps.61874.66663660452837213.88feed53-4335-4b35-8a3a-476a0f0fd6ca.2fb76fcc-ce28-470d-b90d-e5285e6ed205',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Pokémon Scarlet and Violet',
      description: 'The latest entries in the Pokémon series, featuring an open-world environment where players can explore various regions, catch new Pokémon, and engage in battles.',
      image_url: 'https://scarletviolet.pokemon.com/images/meta/en/share-tw.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Pokémon Sword and Shield',
      description: 'The first Pokémon games for the Nintendo Switch, introducing the Galar region. Players catch and train Pokémon while battling rivals, challenging gyms, and exploring the new open-world areas.',
      image_url: 'https://e.snmc.io/i/1200/s/d697f052176e7e76842068e374039232/7841581',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Portal 2',
      description: 'A first-person puzzle-platformer where players use a portal gun to navigate complex environments. The game features clever puzzles and witty dialogue as players assist a personality core named GLaDOS.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Portal2cover.jpg',
      platform: ['PlayStation 3', 'Xbox 360', 'PC', 'Mac'],
      release_year: 2011,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Prey',
      description: 'A first-person action-adventure game set aboard a space station overrun by hostile aliens. Players use a combination of weapons, abilities, and strategy to survive and uncover the station\'s dark secrets.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/2/29/Prey_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Prey (2017)',
      description: 'A reboot of the Prey franchise, focusing on first-person exploration, combat, and puzzle-solving. Set in a space station under siege by alien creatures, the protagonist uncovers the mysteries of the station.',
      image_url: 'https://static.wikia.nocookie.net/prey/images/f/fc/Art_of_Prey_cover.jpg/revision/latest?cb=20180403143345',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Rainbow Six Siege',
      description: 'A tactical first-person shooter where players control elite counter-terrorism operatives, each with unique abilities. The game emphasizes strategy, teamwork, and destructible environments.',
      image_url: 'https://store.ubisoft.com/on/demandware.static/-/Sites-masterCatalog/default/dw63e24d90/images/large/56c494ad88a7e300458b4d5a.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ratchet & Clank: QForce',
      description: 'A platformer with a focus on combat, puzzle-solving, and exploration, where Ratchet and his robotic companion Clank defend the galaxy from an invading force.',
      image_url: 'https://gamefaqs.gamespot.com/a/box/5/9/7/609597_front.jpg',
      platform: ['PlayStation 3', 'PlayStation Vita'],
      release_year: 2012,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ratchet & Clank: Rift Apart',
      description: 'The latest entry in the Ratchet & Clank series, offering fast-paced action, exploration, and dimension-hopping mechanics, with beautiful graphics and a fun storyline.',
      image_url: 'https://image.api.playstation.com/vulcan/ap/rnd/202101/2921/CrGbGyUFNdkZKbg9DM2qPTE1.jpg',
      platform: ['PlayStation 5'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Red Dead Redemption 2',
      description: 'An open-world action-adventure game set in the Wild West, where players control Arthur Morgan, a member of the Van der Linde gang. The game features detailed storytelling, exploration, and a deep combat system.',
      image_url: 'https://assets.vg247.com/current//2018/05/red_dead_redemption_2_cover_art_1.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Stadia'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Resident Evil Village',
      description: 'The eighth main entry in the Resident Evil series, where players control Ethan Winters as he searches for his kidnapped daughter in a terrifying village filled with horrific creatures.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/2/2c/Resident_Evil_Village.png',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Returnal',
      description: 'A rogue-like third-person shooter where players control Selene, a space explorer trapped on an alien planet. The game features fast-paced combat, procedurally generated environments, and a deep narrative.',
      image_url: 'https://image.api.playstation.com/vulcan/ap/rnd/202011/1621/4ItSbqJE88H019Ua3WBQKLF8.png',
      platform: ['PlayStation 5'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Ring Fit Adventure',
      description: 'A fitness-based adventure game where players use a ring-shaped controller to perform exercises and defeat enemies. The game combines exercise with RPG mechanics as players progress through levels and work on their fitness.',
      image_url: 'https://supergamestation.com/cdn/shop/products/Ringfit_420x.png?v=1653681842',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Rocket League',
      description: 'A unique sports game that blends soccer with rocket-powered cars. Players can perform acrobatic maneuvers to score goals in fast-paced multiplayer matches.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/1/13/Rocket_League_cover.png',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC', 'PlayStation 5', 'Xbox Series X/S'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sackboy: A Big Adventure',
      description: 'A platformer starring Sackboy from the LittleBigPlanet series, with players navigating through creative levels filled with obstacles, enemies, and puzzles. The game focuses on fun and cooperative play.',
      image_url: 'https://cdn1.epicgames.com/offer/1b60f39de33b4902a8d5fa543b1fb628/EGS_SackboyABigAdventure_SumoDigital_S2_1200x1600-cc68022e4d17a383c8571dc43586353c',
      platform: ['PlayStation 4', 'PlayStation 5'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sea of Thieves',
      description: 'An open-world multiplayer pirate adventure where players team up to sail the seas, hunt for treasure, and battle other crews. The game features a living world with dynamic events and plenty of exploration.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/7/77/Sea_of_thieves_cover_art.jpg',
      platform: ['Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sekiro: Shadows Die Twice',
      description: 'An action-adventure game set in feudal Japan where players control a shinobi on a mission to rescue his kidnapped lord. The game features challenging combat, stealth mechanics, and a deep storyline.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Sekiro_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Stadia'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shadow of the Tomb Raider',
      description: 'The final entry in the Tomb Raider reboot trilogy, where Lara Croft must face her enemies and uncover the secrets of the ancient tombs to stop a Mayan apocalypse.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/1/11/Shadow_of_the_Tomb_Raider_cover.png',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Stadia'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shantae: Half-Genie Hero',
      description: 'A colorful, action-platformer starring Shantae, a half-genie hero. Players use Shantae\'s transforming abilities to battle enemies and explore vibrant worlds in this critically acclaimed indie game.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/9/9c/Shantae_Half-Genie_Hero.png',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Shovel Knight: Treasure Trove',
      description: 'A retro-style platformer that features a knight armed with a shovel. The game is filled with action, exploration, and boss battles, and includes multiple campaigns with different characters.',
      image_url: 'https://static.wikia.nocookie.net/shovelknight/images/e/ea/Treasure_Trove_Cover_Art.png/revision/latest?cb=20180831020244',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sid Meier\'s Civilization VI',
      description: 'A turn-based strategy game where players lead a civilization from the ancient era to the modern age. The game focuses on city-building, diplomacy, and warfare, with multiple paths to victory.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Civilization_VI_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC', 'Mac'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sifu',
      description: 'An action game where players take on the role of a martial artist seeking revenge for the death of their family. The game features hand-to-hand combat, time-based aging mechanics, and an emphasis on skill progression.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/e/e3/Sifu_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Skyward Sword HD',
      description: 'A remastered version of The Legend of Zelda: Skyward Sword, featuring motion controls or traditional button controls for combat and puzzle-solving. Link embarks on a journey to find Zelda and defeat evil forces.',
      image_url: 'https://m.media-amazon.com/images/I/71hMCkiKCdL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'South Park: The Fractured But Whole',
      description: 'A turn-based RPG where players control a new character in the South Park universe. The game parodies superhero tropes, allowing players to create their own superhero and engage in comedic adventures.',
      image_url: 'https://m.media-amazon.com/images/I/81-ql8urZOL._AC_UF1000,1000_QL80_.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Spider-Man: Miles Morales',
      description: 'A superhero action game where players control Miles Morales as he steps up to become Spider-Man. The game features fast-paced combat, web-slinging, and a compelling story set in a snowy New York City.',
      image_url: 'https://m.media-amazon.com/images/I/616swVHnhHL._AC_UF894,1000_QL80_.jpg',
      platform: ['PlayStation 4', 'PlayStation 5'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Splatoon 3',
      description: 'A third-person multiplayer shooter where players control squid-like characters who engage in turf wars. The game includes new weapons, modes, and customization options for players.',
      image_url: 'https://m.media-amazon.com/images/I/81OSkSH-qgL.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Star Wars Jedi: Fallen Order',
      description: 'An action-adventure game set in the Star Wars universe, where players control Cal Kestis, a young Jedi who is trying to survive after the events of Revenge of the Sith. The game combines exploration, platforming, and lightsaber combat.',
      image_url: 'https://m.media-amazon.com/images/I/71DqeQdrUBL._AC_UF1000,1000_QL80_.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Stadia'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Starcraft II',
      description: 'A real-time strategy game set in a futuristic universe where players control one of three factions in a battle for supremacy. The game focuses on resource management, tactical combat, and strategic gameplay.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/2/20/StarCraft_II_-_Box_Art.jpg',
      platform: ['PC', 'Mac'],
      release_year: 2010,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Stardew Valley',
      description: 'A farming simulation game where players inherit a run-down farm and work to restore it to its former glory. The game includes farming, mining, fishing, and building relationships with townspeople.',
      image_url: 'https://m.media-amazon.com/images/I/71IcDLw+8UL.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC', 'Mobile'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'State of Decay 2',
      description: 'An open-world survival game set in a post-apocalyptic world overrun by zombies. Players must build a community, gather resources, and fight to survive in an ever-changing environment.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/9/9d/State_of_Decay_2_art.jpg',
      platform: ['Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Stray',
      description: 'An adventure game where players control a stray cat in a dystopian world. The game features exploration, puzzle-solving, and platforming, with the goal of uncovering the secrets of the futuristic city.',
      image_url: 'https://preview.redd.it/is-there-anywhere-i-can-commission-artwork-of-the-stray-v0-mpcdmptfkl3a1.jpg?width=499&format=pjpg&auto=webp&s=20a02c1a132422f9105d1af00ee4049bb9a59555',
      platform: ['PlayStation 4', 'PlayStation 5', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Subnautica',
      description: 'A survival game set in an alien underwater world. Players must explore the depths of the ocean, gather resources, and build a base while avoiding dangerous creatures.',
      image_url: 'https://m.media-amazon.com/images/I/61kvBWs9feL._AC_UF894,1000_QL80_.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Nintendo Switch'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Sunset Overdrive',
      description: 'An open-world action game set in a vibrant, chaotic city after an energy drink turns people into mutants. Players control a character who uses over-the-top weapons and acrobatic moves to fight enemies and cause havoc.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/4/46/Sunset_Overdrive_cover.jpg',
      platform: ['Xbox One', 'PC'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Super Bomberman R',
      description: 'A multiplayer-focused action game where players control Bomberman characters to place bombs and eliminate opponents in a grid-based arena. The game features both local and online play.',
      image_url: 'https://m.media-amazon.com/images/I/81E6VFqVh+L.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Super Lucky\'s Tale',
      description: 'A 3D platformer where players control Lucky, a cute fox on a quest to rescue his friends. The game features colorful worlds, fun puzzles, and tight platforming action.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/b/b1/Super_Lucky%27s_Tale.jpg',
      platform: ['Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Super Mario 3D World + Bowser’s Fury',
      description: 'A re-release of the Super Mario 3D World game with added content, including Bowser\'s Fury, an open-world adventure where Mario teams up with Bowser Jr. to stop Bowser\'s rampage.',
      image_url: 'https://m.media-amazon.com/images/I/91vyVfjkQzS._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Super Mario Maker 2',
      description: 'A game that allows players to create, share, and play custom Mario levels. It includes new tools, features, and a robust online mode for sharing creations with the community.',
      image_url: 'https://m.media-amazon.com/images/I/71WHPxzenhL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Super Mario Odyssey',
      description: 'A 3D platformer where Mario embarks on a globe-trotting adventure to save Princess Peach and stop Bowser. The game introduces new mechanics, such as using Mario’s hat to possess enemies and objects.',
      image_url: 'https://target.scene7.com/is/image/Target/GUEST_0d151669-8465-4a77-b1d5-d0850f63c391?wid=488&hei=488&fmt=pjpeg',
      platform: ['Nintendo Switch'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Super Mario Party',
      description: 'A party game featuring a variety of mini-games where players compete in challenges to collect coins and stars. It offers both competitive and cooperative multiplayer gameplay.',
      image_url: 'https://m.media-amazon.com/images/I/71JihhBmbvL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Super Smash Bros. Ultimate',
      description: 'A crossover fighting game featuring a massive roster of characters from various video game franchises. Players battle in dynamic arenas with a focus on fun, fast-paced combat.',
      image_url: 'https://m.media-amazon.com/images/I/81gTTc2IpCL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Tales of Arise',
      description: 'An action RPG that follows two protagonists as they seek to overthrow an oppressive regime. The game features fast-paced combat, an engaging story, and rich world-building.',
      image_url: 'https://m.media-amazon.com/images/M/MV5BODY4ZjRlNDItZmViZC00ZjE3LWE3NjEtY2IxMTAyMzU3YmMxXkEyXkFqcGc@._V1_.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2021,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Tchia',
      description: 'An open-world adventure game where players control Tchia, a young girl with the ability to possess animals and objects. The game features exploration, puzzle-solving, and a vibrant tropical island setting.',
      image_url: 'https://m.media-amazon.com/images/M/MV5BNjFiMTZiNDMtMjUzYS00NjI4LTk2ZGYtMDFjODk5NTlmMGI0XkEyXkFqcGc@._V1_.jpg',
      platform: ['PlayStation 5', 'PC'],
      release_year: 2023,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Tetris 99',
      description: 'A competitive version of the classic Tetris puzzle game, where 99 players compete against each other in real-time to be the last one standing. The game features strategic elements such as targeting opponents and sending blocks their way.',
      image_url: 'https://m.media-amazon.com/images/I/81kUPqIXnwL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Tetris Effect: Connected',
      description: 'A visually stunning and immersive version of the classic Tetris puzzle game, enhanced with beautiful backgrounds, music, and unique modes that elevate the traditional gameplay.',
      image_url: 'https://cdn1.epicgames.com/offer/76339caf9e8e4d24b62761c736e82b42/EGS_TetrisEffectConnected_MonstarsincResonairStageGames_S2_1200x1600-198972bf794d088c3cb15e71bac9f0e2',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Banner Saga',
      description: 'A tactical RPG set in a Viking-inspired world where players control a caravan of survivors fleeing from an ancient threat. The game features strategic combat, branching choices, and a rich narrative.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/6/63/The_Banner_Saga_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Banner Saga 3',
      description: 'The final entry in The Banner Saga series, continuing the story of survival, war, and political intrigue. It features tactical combat and choices that influence the fate of the characters and the world.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/26/The_Banner_Saga_3_cover_art.jpeg/220px-The_Banner_Saga_3_cover_art.jpeg',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2018,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Binding of Isaac: Afterbirth+',
      description: 'An action roguelike game where players control Isaac as he ventures into randomly generated dungeons, battling enemies and bosses while collecting items that alter gameplay.',
      image_url: 'https://store.nicalis.com/cdn/shop/products/fponlyWebstore_cover_adb7b49b-b0af-4dd1-901c-203a484cc358_grande.png?v=1732304678',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Division 2',
      description: 'A third-person shooter set in a post-apocalyptic Washington D.C., where players take on the role of Division agents to restore order and combat enemies in a war-torn world.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/a/af/The_Division_2_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Elder Scrolls V: Skyrim',
      description: 'An open-world RPG set in the fantasy world of Tamriel, where players assume the role of the Dragonborn and embark on a quest to stop an ancient dragon apocalypse.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png',
      platform: ['PlayStation 3', 'Xbox 360', 'PlayStation 4', 'Xbox One', 'PC', 'Switch'],
      release_year: 2011,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Elder Scrolls V: Skyrim Special Edition',
      description: 'A remastered version of Skyrim, featuring enhanced graphics, bug fixes, and the inclusion of all downloadable content. It offers the same open-world experience with a more polished presentation.',
      image_url: 'https://cdn1.epicgames.com/offer/c8738a4d1ead40368eab9688b3c7d737/EGS_SkyrimSpecialEdition_BethesdaGameStudios_S2_1200x1600-ae5d13f6510e81460fe80aa1ca19cf4c',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Switch'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Last of Us Part I',
      description: 'A remake of the original The Last of Us, featuring improved graphics, gameplay mechanics, and enhanced AI. The game follows Joel and Ellie as they navigate a post-apocalyptic world filled with infected and hostile survivors.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Last_of_Us_Part_I_cover.jpg',
      platform: ['PlayStation 5'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Legend of Zelda: Breath of the Wild',
      description: 'An open-world action-adventure game where players control Link in a vast, explorable world. The game features non-linear gameplay, puzzle-solving, combat, and exploration as Link attempts to defeat Calamity Ganon and save Hyrule.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg',
      platform: ['Nintendo Switch', 'Wii U'],
      release_year: 2017,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Legend of Zelda: Link\'s Awakening (Remake)',
      description: 'A remake of the classic Link\'s Awakening game with a unique toy-like art style. Players control Link as he explores the island of Koholint, solving puzzles and battling enemies to awaken the Wind Fish.',
      image_url: 'https://m.media-amazon.com/images/I/71XfeZI6JwL._AC_UF1000,1000_QL80_.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Pathless',
      description: 'An action-adventure game where players control a hunter and her eagle companion as they explore a vast, mystical island to break a curse. The game features fluid movement and combat, with an emphasis on exploration and puzzle-solving.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/6/63/The_Pathless_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Sims 4',
      description: 'A life simulation game where players create and control virtual people (Sims), managing their relationships, careers, and daily activities in a simulated world. The game offers various expansions, mods, and customization options.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7f/Sims4_Rebrand.png/220px-Sims4_Rebrand.png',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Mac'],
      release_year: 2014,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Witcher 2: Assassins of Kings',
      description: 'An action RPG set in the dark fantasy world of The Witcher. Players control Geralt of Rivia as he investigates political intrigue and battles monsters. The game features branching choices, combat, and a rich narrative.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/4/40/Witcher_2_cover.jpg',
      platform: ['PC', 'Xbox 360'],
      release_year: 2011,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Witcher 3: Wild Hunt',
      description: 'An open-world RPG where players control Geralt of Rivia, a monster hunter, as he searches for his adopted daughter while battling enemies, solving quests, and uncovering a dark conspiracy.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC', 'Switch'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Witcher 3: Wild Hunt (Next-Gen Update)',
      description: 'A next-gen update for The Witcher 3: Wild Hunt featuring enhanced graphics, improved gameplay features, and performance optimizations. It offers an even more immersive experience of the game’s vast world.',
      image_url: 'https://xxboxnews.blob.core.windows.net/prod/sites/2/2022/11/Witcher_3_Next_Gen_RGB_flattened-193259cb2b197bdb1ca2.jpg',
      platform: ['PlayStation 5', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'The Witcher 3: Wild Hunt – Complete Edition',
      description: 'The Complete Edition includes the base game and both major expansions, Hearts of Stone and Blood and Wine. It offers the complete experience of Geralt’s journey with new areas, quests, and narrative content.',
      image_url: 'https://cdn1.epicgames.com/offer/14ee004dadc142faaaece5a6270fb628/EGS_TheWitcher3WildHuntCompleteEdition_CDPROJEKTRED_S2_1200x1600-53a8fb2c0201cd8aea410f2a049aba3f',
      platform: ['PlayStation 4', 'Xbox One', 'Nintendo Switch', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Titanfall 2',
      description: 'A first-person shooter that combines fast-paced infantry combat with giant mechs called Titans. The game features a compelling single-player campaign and engaging multiplayer modes.',
      image_url: 'https://i.ebayimg.com/images/g/EZUAAOSwdZxlBnse/s-l1200.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Tom Clancy\'s Rainbow Six Siege',
      description: 'A tactical first-person shooter where players take on the roles of various operators with unique abilities. The game focuses on team-based strategies, where players work together to breach, defend, and complete objectives.',
      image_url: 'https://m.media-amazon.com/images/I/61BlQmnK8XS._AC_UF894,1000_QL80_.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2015,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Total War: Three Kingdoms',
      description: 'A strategy game set during the Three Kingdoms period of China, where players control one of several factions and lead them to victory through military tactics, diplomacy, and strategy.',
      image_url: 'https://m.media-amazon.com/images/I/81M36A9X-GL._AC_UF1000,1000_QL80_.jpg',
      platform: ['PC'],
      release_year: 2019,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Tunic',
      description: 'An action-adventure game where players control a small fox exploring a mysterious island. The game features challenging combat, puzzles, and exploration, all while slowly uncovering the world’s lore.',
      image_url: 'https://cdn1.epicgames.com/offer/b6faa05b8b594ec39944ff71dbdfdfc1/EGS_TUNIC_ISOMETRICORPGamesLtd_S2_1200x1600-a3686b673e7a78a0e5bd33f7cecd598e',
      platform: ['Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'UFC 4',
      description: 'A mixed martial arts fighting game that focuses on creating a personalized fighter and competing in various modes, including a career mode and online play.',
      image_url: 'https://mms.businesswire.com/media/20200711005004/en/804751/4/Copy_of_EASUFC4keyartRGBvert.jpg',
      platform: ['PlayStation 4', 'Xbox One'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Valorant',
      description: 'A tactical first-person shooter that emphasizes team-based strategy and precise aiming. Players select "agents" with unique abilities and work together to complete objectives in a competitive multiplayer environment.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/b/ba/Valorant_cover.jpg',
      platform: ['PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Warframe',
      description: 'A free-to-play online game where players control robotic warriors known as "Warframes" as they battle through various missions across the solar system. The game features co-op gameplay, exploration, and intense combat.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/b/bd/Warframe_Cover_Art.png',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'Nintendo Switch', 'PC'],
      release_year: 2013,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Watch Dogs 2',
      description: 'An open-world action-adventure game where players control Marcus Holloway, a hacker trying to take down a corrupt surveillance system. The game features stealth, hacking, and driving mechanics in a sprawling San Francisco setting.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/b/b0/Watch_Dogs_2.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Watch Dogs: Legion',
      description: 'Set in a dystopian near-future London, Watch Dogs: Legion allows players to control anyone in the city, building a resistance against an authoritarian regime. The game features open-world exploration and hacking mechanics.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/d/dc/Watch_Dogs_Legion_cover_art.webp',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'XCOM 2',
      description: 'A turn-based strategy game where players control a resistance group fighting against an alien occupation of Earth. The game features tactical combat, base management, and a rich narrative with branching decisions.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/c/c3/XCOM_2_cover_art.jpg',
      platform: ['PlayStation 4', 'Xbox One', 'PC'],
      release_year: 2016,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Xenoblade Chronicles 3',
      description: 'An action RPG that follows a group of characters from two warring nations who must uncover the truth behind their world’s conflict. The game features real-time combat, exploration, and a rich story set in an expansive open world.',
      image_url: 'https://m.media-amazon.com/images/I/81AS-lQdqfL.jpg',
      platform: ['Nintendo Switch'],
      release_year: 2022,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      title: 'Yakuza: Like a Dragon',
      description: 'A turn-based RPG that takes place in the Yakuza universe, where players control Ichiban Kasuga, a former yakuza member on a journey to uncover the truth behind his betrayal. The game features a colorful cast of characters, a deep narrative, and various side activities.',
      image_url: 'https://upload.wikimedia.org/wikipedia/en/2/2f/Yakuza_like_a_dragon_cover_art.jpg',
      platform: ['PlayStation 4', 'PlayStation 5', 'Xbox One', 'Xbox Series X/S', 'PC'],
      release_year: 2020,
      createdAt: new Date(),
      updatedAt: new Date(),
    }    
];

await Game.insertMany(gameData)

  console.log("Users have been seeded!");

  process.exit();
});
